apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm4s-dev
resources:
  - ../../deployment.yaml
  - ../../service.yaml
images:
  - name: llm4s/safe-deployment
    newName: ghcr.io/llm4s/llm4s/safe-deployment
    newTag: dev
